### ISSUE TITLE
Take the constants that Kai gave to use about the arm and put them in the code.

### ISSUE THREAD

**Issue by cml1010101** [NorthernForce/ChargedUp#76]
Length of extended and retracted should be in doubles, fulcrum point a translation2d

**Comment by christianr-172** [comment]
<img width="1024" alt="Screenshot 2023-02-21 at 7 18 32 PM" src="https://user-images.githubusercontent.com/122945000/221063673-7c395862-7859-424a-b558-0120d4bf59fc.png">
